#!/bin/bash

ROOT=..
echo Checking for SD card
BOOT=$(ls /media)
if [ "$BOOT" = "boot" ]; then
	echo SD card present
else
	echo No SD card present. 
	echo Please insert SD card and try again.
	exit
fi

echo Copying application file to SD card
cp $ROOT/test/binary/test/Release/test_ti.bin /media/boot/app
echo unmounting SD card. Please remove.
umount /dev/sdb1
make clean
